version: '3'
services:

  #PHP Service
  backend:
    build:
      context: .
      # dockerfile: Dockerfile
    image: geosm
    container_name: backend_partie
    restart: unless-stopped
    tty: true
    volumes: 

        - ./docker/public/.env:/var/www/GeoOSM_Backend/projet_laravel/.env
        - ./docker/public/assets/config.js:/var/www/GeoOSM_Backend/projet_laravel/public/assets/config.js
        - ./docker/public/assets/images/:/var/www/GeoOSM_Backend/projet_laravel/public/assets/images/
        - ./docker/public/assets/admin/images/:/var/www/GeoOSM_Backend/projet_laravel/public/assets/admin/images/
        - ./docker/public/upload/:/var/www/GeoOSM_Backend/projet_laravel/public/upload

        - ./docker/client/environment.ts:/var/www/GeoOSM_Frontend/src/environments/environment.ts
        - ./docker/client/htaccess.txt:/var/www/GeoOSM_Frontend/htaccess.txt
        - ./docker/client/assets:/var/www/GeoOSM_Frontend/assets

        - ./docker/php/php.ini:/etc/php/7.4/cli/conf.d/30local.ini 
        - ./docker/vhost-apache/:/etc/apache2/sites-available/
        - ./docker/boot.sh:/var/www/boot.sh

    environment:
        DEFAULT_ROOT: "/"
        WEB_ROOT: /var/www/GeoOSM_Frontend/dist/
    ports:
        - "80:80"
